services:
  - type: web
    name: spicy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    branch: master
